app:
  id: ttk-file-server #应用的唯一标识，必须和网页上的一一对应
apollo:
  meta: http://192.168.137.180:8080 #加入meta地址，在主页上有该信息
  bootstrap:
    namespaces: application
    enabled: true  #默认注入application NameSpace的配置
    eagerLoad:
      enabled: true #将配置的加载提到日志初始化之前
